### ISSUE TITLE
GUI stopped working

### ISSUE THREAD

**Issue by vsht** [bordaigorl/remy#25]
Hi,

having upgraded to Fedora 35 (Python 3.10, python-poppler-qt5 21.1.0, PyQt5 5.15.6) I noticed that I cannot start the remy GUI
anymore

```
[I] STARTING: Sun Jan 23 14:34:26 2022

(python:338599): Gtk-WARNING **: 14:34:26.984: Theme parsing error: gtk.css:20:4: Junk at end of value for padding
[I] Configuration loaded from /home/vs/.config/remy/config.json.
[I] LOAD TIME: 0.103348
Traceback (most recent call last):
  File "/media/Data/Software/remy/remy/gui/app.py", line 213, in initialised
    self.tree = FileBrowser(index)
  File "/media/Data/Software/remy/remy/gui/browser/__init__.py", line 211, in __init__
    info = self.info = InfoPanel(index, splitter)
  File "/media/Data/Software/remy/remy/gui/browser/info.py", line 174, in __init__
    self.setEntry()
  File "/media/Data/Software/remy/remy/gui/browser/info.py", line 220, in setEntry
    self.setInfo(**self._defaults)
  File "/media/Data/Software/remy/remy/gui/browser/info.py", line 210, in setInfo
    self.setIcon(QPixmap())
  File "/media/Data/Software/remy/remy/gui/browser/info.py", line 195, in setIcon
    self.icon.setContentsMargins(0, m, 0, m)
TypeError: arguments did not match any overloaded call:
  setContentsMargins(self, int, int, int, int): argument 2 has unexpected type 'float'
  setContentsMargins(self, QMargins): argument 1 has unexpected type 'int'
/home/vs/bin/vsRemyExplore: Zeile 3: 338599 Abgebrochen             (Speicherabzug geschrieben) python /media/Data/Software/remy/remygui.py LocalBackup
```

I'm on the devel branch.

**Comment by bordaigorl** [comment]
Can you try now?

**Comment by vsht** [comment]
Thanks, now it works again! For my part the issue can be closed.
