### ISSUE TITLE
Can not start the app

### ISSUE THREAD

**Issue by tbrandysky** [bordaigorl/remy#26]
I'm trying to run the app on Linux Mint. 

$ python3 remygui.py

[I] STARTING: Fri Feb 18 12:05:45 2022
qt5ct: using qt5ct plugin
[I] Configuration loaded from defaults.
Traceback (most recent call last):
  File "remygui.py", line 4, in <module>
    app.main()
  File "/home/shamot/Downloads/remy-master/remy/gui/app.py", line 364, in main
    app.requestInit()
  File "/home/shamot/Downloads/remy-master/remy/gui/app.py", line 115, in requestInit
    init = RemyInitWorker(*self.config.connectionArgs(**overrides))
  File "/home/shamot/Downloads/remy-master/remy/remarkable/config.py", line 193, in connectionArgs
    t = c.pop('type')
KeyError: 'type'

**Comment by bordaigorl** [comment]
You read my mind :)
The latest commits in devel (now merged in master) try to address this issue.
Basically you are starting remy without a proper configuration, and it crashes instead of giving you meaningful error messages.
If you run the latest version you should instead get some instructions.

**Comment by tbrandysky** [comment]
Great, thank you!
