### ISSUE TITLE
Application can not be executed

### ISSUE THREAD

**Issue by tbrandysky** [bordaigorl/remy#43]
Steps to reproduce the issue:

1. git clone https://github.com/bordaigorl/remy.git
2. cd remy
3. $python3 -m remy.gui

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/shamot/Remarkable2/remy/remy/gui/__main__.py", line 1, in <module>
    from remy.gui import app
  File "/home/shamot/Remarkable2/remy/remy/gui/app.py", line 18, in <module>
    import remy.gui.resources
ModuleNotFoundError: No module named 'remy.gui.resources'

**Comment by tbrandysky** [comment]
Yes, I did. It wasn't clear to me that I also need to perform these steps when I decide for Manual installation steps (https://github.com/bordaigorl/remy#manual-installation)

Anyway, when I try to install the dependencies using pip, it terminates with this error:

$ pip install .
Defaulting to user installation because normal site-packages is not writeable
Processing /home/shamot/Remarkable2/remy
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      running egg_info
      Traceback (most recent call last):
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 162, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 143, in _get_build_requires
          self.run_setup()
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 33, in <module>
          setup(
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 148, in setup
          return run_commands(dist)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 163, in run_commands
          dist.run_commands()
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "setup.py", line 30, in run
          genResources()
        File "setup.py", line 10, in genResources
          from PyQt5.pyrcc_main import main as pyrcc_main
        File "/tmp/pip-build-env-2l2bzxkb/overlay/local/lib/python3.10/dist-packages/PyQt5/pyrcc_main.py", line 23, in <module>
          from .pyrcc import *
      ImportError: /tmp/pip-build-env-2l2bzxkb/overlay/local/lib/python3.10/dist-packages/PyQt5/Qt5/lib/libQt5Xml.so.5: undefined symbol: _ZdlPvm, version Qt_5
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by tbrandysky** [comment]
It seems there was some missing library in my system. Unfortunately, I can't say which one it was but I can confirm everything works as expected

**Comment by bordaigorl** [comment]
Thanks for reporting!
