### ISSUE TITLE
Some Issues

### ISSUE THREAD

**Issue by benneti** [bordaigorl/remy#9]
Hi, 
I am trying to get remy working in nixos.
I already get it to launch but there are still two problems:

if I work with a local copy of my remarkable folders I get as far as to see my notebooks but if I double click any file I get tracebacks of the form:
```
Started
Configuration loaded from '/home/benneti/.config/remy.json'.
LOAD TIME: 0.048436
Traceback (most recent call last):
  File "/nix/store/18h689vj846lh37kk0k6mj70nyi41zvj-remy-0-git/src/remy/gui/filebrowser.py", line 442, in openEntry
    self.viewers[uid] = NotebookViewer(index.get(uid))
  File "/nix/store/18h689vj846lh37kk0k6mj70nyi41zvj-remy-0-git/src/remy/gui/notebookview.py", line 102, in __init__
    self.loadPage(document.lastOpenedPage or 0)
  File "/nix/store/18h689vj846lh37kk0k6mj70nyi41zvj-remy-0-git/src/remy/gui/notebookview.py", line 175, in loadPage
    self._page_cache[i] = self.makePageScene(i, eraser_mode=ermode)
  File "/nix/store/18h689vj846lh37kk0k6mj70nyi41zvj-remy-0-git/src/remy/gui/notebookview.py", line 164, in makePageScene
    PageGraphicsItem(page, scene=scene, simplify=simplify, smoothen=smoothen, eraser_mode=eraser_mode, parent=r)
  File "/nix/store/18h689vj846lh37kk0k6mj70nyi41zvj-remy-0-git/src/remy/gui/pagerender.py", line 154, in __init__
    if eraser_mode >= AUTO_ERASER:
TypeError: '>=' not supported between instances of 'NoneType' and 'int'
/nix/store/18h689vj846lh37kk0k6mj70nyi41zvj-remy-0-git/bin/.remy-gui-wrapped: line 3: 10095 Aborted                 (core dumped) /nix/store/2vjlf8bip418y0d9vglaplfgpz29spd5-python3-3.8.6-env/bin/python /nix/store/18h689vj846lh37kk0k6mj70nyi41zvj-remy-0-git/src/remygui.py $@
```

Also if I try to use rsync (installed via entware) I get
```
Started
Configuration loaded from '/home/benneti/.config/remy.json'.
Connecting...
Connected to 10.11.99.1
DATA STORED IN:
	/home/benneti/.local/share/remy/documents
	/home/benneti/.local/share/remy/templates
Traceback (most recent call last):
  File "/nix/store/18h689vj846lh37kk0k6mj70nyi41zvj-remy-0-git/src/remygui.py", line 4, in <module>
    app.main()
  File "/nix/store/18h689vj846lh37kk0k6mj70nyi41zvj-remy-0-git/src/remy/gui/app.py", line 87, in main
    fsource = fileSourceFromSSH(LiveFileSourceRsync,  **src)
  File "/nix/store/18h689vj846lh37kk0k6mj70nyi41zvj-remy-0-git/src/remy/remarkable/filesource.py", line 480, in fileSourceFromSSH
    return cls(name, client, **kw)
  File "/nix/store/18h689vj846lh37kk0k6mj70nyi41zvj-remy-0-git/src/remy/remarkable/filesource.py", line 367, in __init__
    self._bulk_download(
  File "/nix/store/18h689vj846lh37kk0k6mj70nyi41zvj-remy-0-git/src/remy/remarkable/filesource.py", line 397, in _bulk_download
    return subprocess.run(cmd)
  File "/nix/store/papbnjfxwrdkmz6xfp7v2q7nxyvgcr5l-python3-3.8.6/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/nix/store/papbnjfxwrdkmz6xfp7v2q7nxyvgcr5l-python3-3.8.6/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/nix/store/papbnjfxwrdkmz6xfp7v2q7nxyvgcr5l-python3-3.8.6/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/bin/rsync'
```
or without  `"rsync_path": "/opt/bin/rsync",` in the configuration I get 
```
Started
Configuration loaded from '/home/benneti/.config/remy.json'.
Connecting...
Connected to 10.11.99.1
DATA STORED IN:
	/home/benneti/.local/share/remy/documents
	/home/benneti/.local/share/remy/templates
sh: rsync: command not found
rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
rsync error: error in rsync protocol data stream (code 12) at io.c(228) [Receiver=3.2.3]
Traceback (most recent call last):
  File "/nix/store/18h689vj846lh37kk0k6mj70nyi41zvj-remy-0-git/src/remygui.py", line 4, in <module>
    app.main()
  File "/nix/store/18h689vj846lh37kk0k6mj70nyi41zvj-remy-0-git/src/remy/gui/app.py", line 87, in main
    fsource = fileSourceFromSSH(LiveFileSourceRsync,  **src)
  File "/nix/store/18h689vj846lh37kk0k6mj70nyi41zvj-remy-0-git/src/remy/remarkable/filesource.py", line 480, in fileSourceFromSSH
    return cls(name, client, **kw)
  File "/nix/store/18h689vj846lh37kk0k6mj70nyi41zvj-remy-0-git/src/remy/remarkable/filesource.py", line 373, in __init__
    with open(self._local("templates.json", branch=TEMPLDIR), 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/benneti/.local/share/remy/templates/templates.json
```

I think the latter can simply be fixed by allowing to specify --rsync-path via the configuration, if you want I can implement this one. Pointers for the first problem would be appreciated.

**Comment by bordaigorl** [comment]
Hi thanks for trying reMy and reporting this!

First problem: missing default in config, will push a fix shortly.
Workaround: specify `"eraser_mode": "ignore"` in the `preview` section of your config file.

Second problem: `rsync_path` specifies the path on the *local* machine.
Indeed it would be more useful to be able to supply extra options to rsynch (e.g. --rsync-path).
If you could produce a PR to receive from config an array of extra arguments to be supplied to rsync that would be great. Otherwise I might give it a go in a few days.

**Comment by benneti** [comment]
Now I get a bit further but with
```
Started
Configuration loaded from '/home/benneti/.config/remy.json'.
LOAD TIME: 0.054723
Traceback (most recent call last):
  File "/home/benneti/repos/remy/remy/gui/filebrowser.py", line 442, in openEntry
    self.viewers[uid] = NotebookViewer(index.get(uid))
  File "/home/benneti/repos/remy/remy/gui/notebookview.py", line 99, in __init__
    self._maxPage = document.baseDocument().numPages() - 1
  File "/home/benneti/repos/remy/remy/remarkable/metadata.py", line 262, in baseDocument
    self._pdf.setRenderHint(Poppler.Document.HideAnnotations)
AttributeError: type object 'Document' has no attribute 'HideAnnotations'
remy-gui.sh: line 11: 27096 Aborted                 (core dumped) /nix/store/2vjlf8bip418y0d9vglaplfgpz29spd5-python3-3.8.6-env/bin/python ./remygui.py $@
```

**Comment by bordaigorl** [comment]
That probably has to do with the version of Poppler/python-poppler-qt5 you have installed.
To see if that's only masking other problems, you can safely comment out the `self._pdf.setRenderHint(Poppler.Document.HideAnnotations)` line.

**Comment by benneti** [comment]
thank you for all the quick responses, now it is finally running!

**Comment by bordaigorl** [comment]
@benneti could you tell me what this returns?

    import popplerqt5
    print(popplerqt5.version())
    print(popplerqt5.poppler_version())

Also: by commenting the render hint line, do you see the annotations (e.g. highlighted links) in the rendered pdf?
You may need to check with a pdf with annotations (try with a pdf from arXiv for example)

**Comment by benneti** [comment]
Python 3.8.6 (default, Sep 23 2020, 13:54:27)
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import popplerqt5
>>> print(popplerqt5.version())
(0, 24, 2)
>>> print(popplerqt5.poppler_version())
(20, 12, 1)

**Comment by benneti** [comment]
Can I also ask whether it is possible to export multiple files at once and to export without looking at the preview?
(In rcu it is possible to mark multiple files with shift and then right click export, this is really convenient)

**Comment by benneti** [comment]
![image](https://user-images.githubusercontent.com/11725645/104221523-47d9de00-5441-11eb-83e3-55265a68ff21.png)
![Screenshot from 2021-01-11 19-13-53](https://user-images.githubusercontent.com/11725645/104221591-5cb67180-5441-11eb-8b5f-8ad4fa4212f4.png)
Here two screenshots of my documents, I am not sure what you would like to see here.

**Comment by bordaigorl** [comment]
Thanks. Glad it works now.

> Can I also ask whether it is possible to export multiple files at once and to export without looking at the preview?
> (In rcu it is possible to mark multiple files with shift and then right click export, this is really convenient)

Not at the moment. It's something I want to add but I had no time to do it yet.
Also planned is a bulk import dialog...
